import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import ClientChatbot from "@/components/ClientChatbot";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // <– thêm 600, 700 để hỗ trợ medium và bold
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ClientLayout>{children}</ClientLayout>

        {/* Chatbot Icon & Chat Window (hide on admin pages) */}
        <ClientChatbot />
      </body>
    </html>
  );
}
